apiVersion: v1
kind: ConfigMap
metadata:
  name: time-slicing-config-gb10
  namespace: gpu-operator
data:
  gb10-shared-2: |
    version: v1
    flags:
      migStrategy: none
    sharing:
      timeSlicing:
        renameByDefault: false
        failRequestsGreaterThanOne: true
        resources:
          - name: nvidia.com/gpu
            replicas: 2
